In [7]:
import numpy as np
import tensorflow as tf
from pprint import pprint
tf.__version__

'2.1.0'

In [94]:
# https://www.tensorflow.org/guide/data#consuming_tfrecord_data

In [38]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
pprint(dataset)

it = iter(dataset)
print('from iterator', next(it).numpy())

for elem in dataset:
    pprint(elem)
    pprint(elem.numpy())

<TensorSliceDataset shapes: (), types: tf.int32>
from iterator 8
<tf.Tensor: shape=(), dtype=int32, numpy=8>
8
<tf.Tensor: shape=(), dtype=int32, numpy=3>
3
<tf.Tensor: shape=(), dtype=int32, numpy=0>
0
<tf.Tensor: shape=(), dtype=int32, numpy=8>
8
<tf.Tensor: shape=(), dtype=int32, numpy=2>
2
<tf.Tensor: shape=(), dtype=int32, numpy=1>
1


In [58]:
# can be many tuples but the same dimension
dataset = tf.data.Dataset.from_tensor_slices((np.random.rand(3,2), np.random.rand(3,1), np.random.rand(3,3)))
pprint(dataset)

for elem in dataset:
    pprint(elem)
    print(elem[0].numpy(), elem[1].numpy(), elem[2].numpy())
    
def reduce_func(s,v):
    print('s',s)
    print('v',v[0])
    return s +v[0][1]

# score at the begining, 
dataset.reduce(initial_state=np.float64(0.0), reduce_func=reduce_func).numpy()

<TensorSliceDataset shapes: ((2,), (1,), (3,)), types: (tf.float64, tf.float64, tf.float64)>
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.85083017, 0.50487089])>,
 <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.50880167])>,
 <tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.67665192, 0.49568366, 0.03434172])>)
[0.85083017 0.50487089] [0.50880167] [0.67665192 0.49568366 0.03434172]
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.26958172, 0.70639786])>,
 <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.99648516])>,
 <tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.13447756, 0.30223672, 0.04863193])>)
[0.26958172 0.70639786] [0.99648516] [0.13447756 0.30223672 0.04863193]
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.99141309, 0.18832028])>,
 <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.90281881])>,
 <tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.21992417, 0.26998951, 0.84557368])>)
[0.99141309 0.18832028] [0.90281881] [0.219

1.399589031760338

In [35]:
# can be many tuples but the same dimension
dataset = tf.data.Dataset.from_tensor_slices(({
    'f1':np.random.rand(3,2),
    'f2':np.random.rand(3,1),
    'f3':['a']*3,
    'f4':[('a','b')]*3
}, np.random.rand(3,1),
{
    'f1':np.random.rand(3,2),
    'f2':np.random.rand(3,1),
    'f3':['a']*3,
    'f4':[('a','b')]*3
}))
pprint(dataset)

for elem in dataset:
    pprint(elem)

<TensorSliceDataset shapes: ({f1: (2,), f2: (1,), f3: (), f4: (2,)}, (1,), {f1: (2,), f2: (1,), f3: (), f4: (2,)}), types: ({f1: tf.float64, f2: tf.float64, f3: tf.string, f4: tf.string}, tf.float64, {f1: tf.float64, f2: tf.float64, f3: tf.string, f4: tf.string})>
({'f1': <tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.95685284, 0.22205657])>,
  'f2': <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.50359126])>,
  'f3': <tf.Tensor: shape=(), dtype=string, numpy=b'a'>,
  'f4': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'a', b'b'], dtype=object)>},
 <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.27363377])>,
 {'f1': <tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.88180238, 0.51927149])>,
  'f2': <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.81846554])>,
  'f3': <tf.Tensor: shape=(), dtype=string, numpy=b'a'>,
  'f4': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'a', b'b'], dtype=object)>})
({'f1': <tf.Tensor: shape=(2,), dtype=float64, nump

In [62]:
d1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([3,2]))
d2 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([3,4]))
dataset = tf.data.Dataset.zip((d1,d2))
print(dataset.element_spec)

for elem in dataset:
    pprint(elem)

(TensorSpec(shape=(2,), dtype=tf.float32, name=None), TensorSpec(shape=(4,), dtype=tf.float32, name=None))
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.3892523, 0.650507 ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.10890687, 0.26567245, 0.273324  , 0.9510344 ], dtype=float32)>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.67673707, 0.44649553], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.0352757 , 0.31573665, 0.25847614, 0.28744495], dtype=float32)>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.29928136, 0.03280652], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.34079146, 0.28909087, 0.7984201 , 0.08759177], dtype=float32)>)


In [76]:
d1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([3,2]))
d2 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([3,4]))
dataset = tf.data.Dataset.zip((d1,d2)).map(lambda v1,v2: tf.math.reduce_sum(tf.math.exp(v1))+tf.math.exp(v2))
print(dataset.element_spec)

for elem in dataset:
    pprint(elem)

TensorSpec(shape=(4,), dtype=tf.float32, name=None)
<tf.Tensor: shape=(4,), dtype=float32, numpy=array([5.0533695, 5.578626 , 5.422433 , 4.87272  ], dtype=float32)>
<tf.Tensor: shape=(4,), dtype=float32, numpy=array([4.679704 , 6.189848 , 6.0703855, 4.8973866], dtype=float32)>
<tf.Tensor: shape=(4,), dtype=float32, numpy=array([5.678505 , 5.7348814, 5.250229 , 5.7345314], dtype=float32)>


In [90]:
# https://www.tensorflow.org/api_docs/python/tf/train/Example
# https://www.tensorflow.org/tutorials/load_data/tfrecord
# tf record
dataset = tf.data.TFRecordDataset(filenames=['./data.tfrecord'])
print(dataset)
raw_example = next(iter(dataset))
parsed = tf.train.Example.FromString(raw_example.numpy())
print(type(parsed))

<TFRecordDatasetV2 shapes: (), types: tf.string>
<class 'tensorflow.core.example.example_pb2.Example'>


In [103]:
dataset = tf.data.TextLineDataset(filenames=['./cowper.txt'])
for elem in dataset.take(3):
    pprint(elem)

# interleave?

<tf.Tensor: shape=(), dtype=string, numpy=b"\xef\xbb\xbfAchilles sing, O Goddess! Peleus' son;">
<tf.Tensor: shape=(), dtype=string, numpy=b'His wrath pernicious, who ten thousand woes'>
<tf.Tensor: shape=(), dtype=string, numpy=b"Caused to Achaia's host, sent many a soul">


In [108]:
titanic_lines = tf.data.TextLineDataset(filenames=['./train.csv'])
for line in titanic_lines.take(10):
    print(line.numpy())
    
def survived(line):
    return tf.not_equal(tf.strings.substr(line, 0, 1), "0")

# tf.strings?

print('=====')
survivors = titanic_lines.skip(1).filter(survived)

for line in survivors.take(10):
    print(line.numpy())

b'survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone'
b'0,male,22.0,1,0,7.25,Third,unknown,Southampton,n'
b'1,female,38.0,1,0,71.2833,First,C,Cherbourg,n'
b'1,female,26.0,0,0,7.925,Third,unknown,Southampton,y'
b'1,female,35.0,1,0,53.1,First,C,Southampton,n'
b'0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y'
b'0,male,2.0,3,1,21.075,Third,unknown,Southampton,n'
b'1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n'
b'1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n'
b'1,female,4.0,1,1,16.7,Third,G,Southampton,n'
=====
b'1,female,38.0,1,0,71.2833,First,C,Cherbourg,n'
b'1,female,26.0,0,0,7.925,Third,unknown,Southampton,y'
b'1,female,35.0,1,0,53.1,First,C,Southampton,n'
b'1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n'
b'1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n'
b'1,female,4.0,1,1,16.7,Third,G,Southampton,n'
b'1,male,28.0,0,0,13.0,Second,unknown,Southampton,y'
b'1,female,28.0,0,0,7.225,Third,unknown,Cherbourg,y'
b'1,male,28.0,0,0,35.5,Firs

In [119]:
# https://www.tensorflow.org/api_docs/python/tf/data/experimental/make_csv_dataset
titanic_batches = tf.data.experimental.make_csv_dataset(
    './train.csv', batch_size=4,
    label_name="survived")

for i,batch in enumerate(titanic_batches.take(2)):
    print('batch',i)
    print(batch[0])
    print(batch[1])
    for item in batch[0]:
        pprint(item)
#     for in batch:
#         pprint(feature)

batch 0
OrderedDict([('sex', <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'male', b'male', b'male', b'male'], dtype=object)>), ('age', <tf.Tensor: shape=(4,), dtype=float32, numpy=array([61.,  4., 34., 36.], dtype=float32)>), ('n_siblings_spouses', <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 4, 1, 1], dtype=int32)>), ('parch', <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 0, 2], dtype=int32)>), ('fare', <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 32.3208,  29.125 ,  21.    , 120.    ], dtype=float32)>), ('class', <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'First', b'Third', b'Second', b'First'], dtype=object)>), ('deck', <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'D', b'unknown', b'unknown', b'B'], dtype=object)>), ('embark_town', <tf.Tensor: shape=(4,), dtype=string, numpy=
array([b'Southampton', b'Queenstown', b'Southampton', b'Southampton'],
      dtype=object)>), ('alone', <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'y', 

In [124]:
list_ds = tf.data.Dataset.list_files('*.csv')

for f in list_ds.take(5):
    print(f.numpy())
    
import os
    
def process_path(file_path):
    label = tf.strings.split(file_path, os.sep)[-1]
    return tf.io.read_file(file_path), label

labeled_ds = list_ds.map(process_path)
for item in labeled_ds.take(3):
    print(item)

b'./train.csv'
(<tf.Tensor: shape=(), dtype=string, numpy=b'survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone\n0,male,22.0,1,0,7.25,Third,unknown,Southampton,n\n1,female,38.0,1,0,71.2833,First,C,Cherbourg,n\n1,female,26.0,0,0,7.925,Third,unknown,Southampton,y\n1,female,35.0,1,0,53.1,First,C,Southampton,n\n0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y\n0,male,2.0,3,1,21.075,Third,unknown,Southampton,n\n1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n\n1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n\n1,female,4.0,1,1,16.7,Third,G,Southampton,n\n0,male,20.0,0,0,8.05,Third,unknown,Southampton,y\n0,male,39.0,1,5,31.275,Third,unknown,Southampton,n\n0,female,14.0,0,0,7.8542,Third,unknown,Southampton,y\n0,male,2.0,4,1,29.125,Third,unknown,Queenstown,n\n1,male,28.0,0,0,13.0,Second,unknown,Southampton,y\n0,female,31.0,1,0,18.0,Third,unknown,Southampton,n\n1,female,28.0,0,0,7.225,Third,unknown,Cherbourg,y\n0,male,35.0,0,0,26.0,Second,unknown,Southampton,y\n

In [132]:
dataset = tf.data.Dataset.range(100)
dataset = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)], x))

pprint(list(dataset.take(3).as_numpy_iterator()))
dataset = dataset.padded_batch(4, padded_shapes=(None,))

for batch in dataset.take(2):
    print(batch.numpy())
    print()

[array([], dtype=int64), array([1]), array([2, 2])]
[[0 0 0]
 [1 0 0]
 [2 2 0]
 [3 3 3]]

[[4 4 4 4 0 0 0]
 [5 5 5 5 5 0 0]
 [6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]]



In [135]:
lines = tf.data.TextLineDataset('./train.csv')
# 一个自增的小程序
counter = tf.data.experimental.Counter()

dataset = tf.data.Dataset.zip((counter, lines))
dataset = dataset.shuffle(buffer_size=100)

pprint(list(dataset.take(3).as_numpy_iterator()))

[(24, b'0,male,40.0,0,0,27.7208,First,unknown,Cherbourg,y'),
 (39, b'0,female,18.0,1,0,17.8,Third,unknown,Southampton,n'),
 (38, b'0,male,28.0,2,0,21.6792,Third,unknown,Cherbourg,n')]
